config/routes.rb
class EducationRoleConstraint
  def initialize(education_role)
    @education_role = education_role
  end

  def matches?(request)
    education_role = request.cookies["education_role"]
    case education_role.to_sym
    when :education_owner
      true if @education_role == :education_owner
    when :education_admin
      true if @education_role == :education_admin
    when :education_teacher
      true if @education_role == :education_teacher
    when :education_student
      true if @education_role == :education_student
    else
      false
    end
  end
end

Rails.application.routes.draw do
  resources :chat_conversations
  namespace :api do
    post "sign_in", to: "sessions#create"
    post "sign_up", to: "registrations#create"
    resources :sessions, only: [ :index, :show, :destroy ]
    resource  :password, only: [ :edit, :update ]
    namespace :identity do
      resource :email,              only: [ :edit, :update ]
      resource :email_verification, only: [ :show, :create ]
      resource :password_reset,     only: [ :new, :edit, :create, :update ]
    end
    namespace :authentications do
      resources :events, only: :index
    end

    resources :project_category_appointments
    resources :project_categories
    resources :project_subtask_appointments
    resources :project_subtasks
    resources :project_task_appointments
    resources :project_tasks
    resources :project_group_appointments
    resources :project_groups
  end
  get "up" => "rails/health#show", as: :rails_health_check
  resources :demo, only: [ :index, :new ]
  resources :images, only: [] do
    collection do
      post :editorjs_upload_by_file
      post :editorjs_upload_by_url
    end
  end
  mount MissionControl::Jobs::Engine, at: "/jobs"
  mount Rswag::Ui::Engine => "/api-docs"
  mount Rswag::Api::Engine => "/api-docs"

  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get "sign_out", to: "sessions#sign_out"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [ :index, :show, :destroy ]
  resource  :password, only: [ :edit, :update ]
  namespace :identity do
    resource :email,              only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset,     only: [ :new, :edit, :create, :update ]
  end
  resources :users, only: [ :index, :show, :update ] do
    member do
      get :profile
    end
  end

  # draw for app routes
  root "article_posts#index"
  draw(:education)
  draw(:article)
end

app/models/chat_user.rb
class ChatUser
  include Mongoid::Document
  include Mongoid::Timestamps

  field :user_id, type: String

  # has_and_belongs_to_many :chat_rooms

  def user
    User.where(id: self.user_id)
  end
end

app/controllers/chat_users_controller.rb
class ChatUsersController < ApplicationController
  before_action :set_chat_user, only: %i[ show edit update destroy ]

  # GET /chat_users or /chat_users.json
  def index
    @chat_users = ChatUser.all
  end

  # GET /chat_users/1 or /chat_users/1.json
  def show
  end

  # GET /chat_users/new
  def new
    @chat_user = ChatUser.new
  end

  # GET /chat_users/1/edit
  def edit
  end

  # POST /chat_users or /chat_users.json
  def create
    @chat_user = ChatUser.new(chat_user_params)

    respond_to do |format|
      if @chat_user.save
        format.html { redirect_to chat_user_url(@chat_user), notice: "Chat user was successfully created." }
        format.json { render :show, status: :created, location: @chat_user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chat_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chat_users/1 or /chat_users/1.json
  def update
    respond_to do |format|
      if @chat_user.update(chat_user_params)
        format.html { redirect_to chat_user_url(@chat_user), notice: "Chat user was successfully updated." }
        format.json { render :show, status: :ok, location: @chat_user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chat_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chat_users/1 or /chat_users/1.json
  def destroy
    @chat_user.destroy!

    respond_to do |format|
      format.html { redirect_to chat_users_url, notice: "Chat user was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat_user
      @chat_user = ChatUser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chat_user_params
      params.require(:chat_user).permit(:user_id)
    end
end

app/views/chat_users/_chat_user.html.erb
<div id="<%= dom_id chat_user %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= chat_user.user_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this chat user", chat_user, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this chat user", edit_chat_user_path(chat_user), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/chat_users/_form.html.erb
<%= form_with(model: chat_user, class: "contents") do |form| %>
  <% if chat_user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(chat_user.errors.count, "error") %> prohibited this chat_user from being saved:</h2>

      <ul>
        <% chat_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/chat_users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing chat user</h1>

  <%= render "form", chat_user: @chat_user %>

  <%= link_to "Show this chat user", @chat_user, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to chat users", chat_users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/chat_users/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Chat users</h1>
    <%= link_to "New chat user", new_chat_user_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="chat_users" class="min-w-full">
    <% @chat_users.each do |chat_user| %>
      <%= render(partial: 'chat_user', locals: { chat_user: chat_user }) %>
    <% end %>
  </div>
</div>

app/views/chat_users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New chat user</h1>

  <%= render "form", chat_user: @chat_user %>

  <%= link_to "Back to chat users", chat_users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/chat_users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @chat_user %>

    <%= link_to "Edit this chat_user", edit_chat_user_path(@chat_user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this chat_user", chat_user_path(@chat_user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to chat_users", chat_users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>