config/routes.rb
class EducationRoleConstraint
  def initialize(education_role)
    @education_role = education_role
  end

  def matches?(request)
    education_role = request.cookies["education_role"]
    case education_role.to_sym
    when :education_owner
      true if @education_role == :education_owner
    when :education_admin
      true if @education_role == :education_admin
    when :education_teacher
      true if @education_role == :education_teacher
    when :education_student
      true if @education_role == :education_student
    else
      false
    end
  end
end

Rails.application.routes.draw do
  resources :chat_conversations
  namespace :api do
    post "sign_in", to: "sessions#create"
    post "sign_up", to: "registrations#create"
    resources :sessions, only: [ :index, :show, :destroy ]
    resource  :password, only: [ :edit, :update ]
    namespace :identity do
      resource :email,              only: [ :edit, :update ]
      resource :email_verification, only: [ :show, :create ]
      resource :password_reset,     only: [ :new, :edit, :create, :update ]
    end
    namespace :authentications do
      resources :events, only: :index
    end

    resources :project_category_appointments
    resources :project_categories
    resources :project_subtask_appointments
    resources :project_subtasks
    resources :project_task_appointments
    resources :project_tasks
    resources :project_group_appointments
    resources :project_groups
  end
  get "up" => "rails/health#show", as: :rails_health_check
  resources :demo, only: [ :index, :new ]
  resources :images, only: [] do
    collection do
      post :editorjs_upload_by_file
      post :editorjs_upload_by_url
    end
  end
  mount MissionControl::Jobs::Engine, at: "/jobs"
  mount Rswag::Ui::Engine => "/api-docs"
  mount Rswag::Api::Engine => "/api-docs"

  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get "sign_out", to: "sessions#sign_out"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [ :index, :show, :destroy ]
  resource  :password, only: [ :edit, :update ]
  namespace :identity do
    resource :email,              only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset,     only: [ :new, :edit, :create, :update ]
  end
  resources :users, only: [ :index, :show, :update ] do
    member do
      get :profile
    end
  end

  # draw for app routes
  root "article_posts#index"
  draw(:education)
  draw(:article)
end

app/models/category_appointment.rb
class CategoryAppointment < ApplicationRecord
  belongs_to :category
  belongs_to :appoint_to, polymorphic: true
end

app/controllers/category_appointments_controller.rb
class CategoryAppointmentsController < ApplicationController
  before_action :set_category_appointment, only: %i[ show edit update destroy ]

  # GET /category_appointments or /category_appointments.json
  def index
    @category_appointments = CategoryAppointment.all
  end

  # GET /category_appointments/1 or /category_appointments/1.json
  def show
  end

  # GET /category_appointments/new
  def new
    @category_appointment = CategoryAppointment.new
  end

  # GET /category_appointments/1/edit
  def edit
  end

  # POST /category_appointments or /category_appointments.json
  def create
    @category_appointment = CategoryAppointment.new(category_appointment_params)

    respond_to do |format|
      if @category_appointment.save
        format.html { redirect_to @category_appointment, notice: "Category appointment was successfully created." }
        format.json { render :show, status: :created, location: @category_appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category_appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /category_appointments/1 or /category_appointments/1.json
  def update
    respond_to do |format|
      if @category_appointment.update(category_appointment_params)
        format.html { redirect_to @category_appointment, notice: "Category appointment was successfully updated." }
        format.json { render :show, status: :ok, location: @category_appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category_appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /category_appointments/1 or /category_appointments/1.json
  def destroy
    @category_appointment.destroy!

    respond_to do |format|
      format.html { redirect_to category_appointments_path, status: :see_other, notice: "Category appointment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category_appointment
      @category_appointment = CategoryAppointment.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_appointment_params
      params.expect(category_appointment: [ :category_id, :appoint_to_id, :appoint_to_type ])
    end
end

app/views/category_appointments/_category_appointment.html.erb
<div id="<%= dom_id category_appointment %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= category_appointment.category_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category appointmentable:</strong>
    <%= category_appointment.appoint_to_id %>
  </p>

</div>

app/views/category_appointments/_form.html.erb
<%= form_with(model: category_appointment, class: "contents") do |form| %>
  <% if category_appointment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category_appointment.errors.count, "error") %> prohibited this category_appointment from being saved:</h2>

      <ul>
        <% category_appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :category_id %>
    <%= form.text_field :category_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :appoint_to_id %>
    <%= form.text_field :appoint_to_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit "Save", class: "rounded-lg py-3 px-5 bg-slate-800 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/category_appointments/edit.html.erb
<div class="mx-auto w-4/5 mt-10">
  <h1 class="font-bold text-2xl">Editing category appointment</h1>

  <%= render "form", category_appointment: @category_appointment %>

  <%= link_to "Show this category appointment", @category_appointment, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to category appointments", category_appointments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/category_appointments/index.html.erb
<div class="w-full">
  <% content_for :title, "Category appointments" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-2xl">Category appointments</h1>
    <%= link_to "New category appointment", new_category_appointment_path, class: "rounded-lg py-3 px-5 bg-slate-800 text-white block font-medium" %>
  </div>

  <div id="category_appointments" class="min-w-full">
    <% @category_appointments.each do |category_appointment| %>
      <%= render category_appointment %>
      <p>
        <%= link_to "Show this category appointment", category_appointment, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/category_appointments/new.html.erb
<div class="mx-auto w-4/5 mt-10">
  <h1 class="font-bold text-2xl">New category appointment</h1>

  <%= render "form", category_appointment: @category_appointment %>

  <%= link_to "Back to category appointments", category_appointments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/category_appointments/show.html.erb
<div class="mx-auto w-4/5 flex">
  <div class="mx-auto">
    <%= render @category_appointment %>

    <%= link_to "Edit this category appointment", edit_category_appointment_path(@category_appointment), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to category appointments", category_appointments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this category appointment", @category_appointment, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>